/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.addtopic;
import database.database;
import database.dbconnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sandesh
 * 
 */

public class addquestion extends javax.swing.JDialog {

    /**
     * Creates new form addquestion
     */
       String faculty = "";
       String section =  "";
       String semester =  "";
       String lecture =  "";
       String deadline =  "";
       int s = 0;
    public addquestion(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        add.setVisible(false);
        update.setVisible(false);
        
    }
    public addquestion(ArrayList sand) {
        
        initComponents();
        add.setVisible(false);
        update.setVisible(false);
                faculty = sand.get(0).toString();
                section =  sand.get(1).toString();
                semester =  sand.get(2).toString();
                lecture =  sand.get(3).toString();
                deadline =  sand.get(4).toString();
       
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        question = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Question");
        setResizable(false);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setText("Add Question");

        question.setColumns(20);
        question.setRows(5);

        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setText("ASSIGN");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("VIEW OPTION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addContainerGap(573, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update)
                        .addGap(133, 133, 133)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      

         if (!"".equals(this.question.getText())) {

            ArrayList datatosend = new ArrayList();
            
            

            datatosend = Assigndata();
           
            
            database dbopt = new database();
            try {
                dbopt.saveDatatoassign(datatosend);
                addquestion dialog = new addquestion(new javax.swing.JFrame(), false );
                dialog.setVisible(false);
            } catch (ParseException ex) {
                System.out.println("operaion error:");// Logger.getLogger(addnewstudent.class.getName()).log(Level.SEVERE, null, ex);

            }

        }
        else
        JOptionPane.showMessageDialog(this,
            "Assign Question ",
            "Message", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbconnect dbcon = new dbconnect();
        try {
            
            ArrayList data = new ArrayList();
            data.add(faculty);
            data.add(section);
            
            data.add(semester);
            
            data.add(lecture);
            database dopt = new database();
            ResultSet check = null;
            check = dopt.getquestion(data);
            if(check.next())
            {
               
                s = check.getInt("id");
                add.setVisible(false);
                update.setVisible(true);
                dbcon.closeConnection();
                
            }
            else{
                update.setVisible(false);
                add.setVisible(true);
               dbcon.closeConnection();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ADDTOPIC.class.getName()).log(Level.SEVERE, null, ex);
            dbcon.closeConnection();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(!"".equals(this.question.getText()))   
      {
                   ArrayList datatosend = new ArrayList();

                                datatosend = Assigndata();
                                //System.out.println("size" + datatosend.size());
                                database dbopt = new database();
                                dbopt.updatequestion(datatosend,s);
      }
      else
      {
      JOptionPane.showMessageDialog(this,
                                        "Topic is Empty "
                                                + "Add Some Question ",
                                        "Message", JOptionPane.INFORMATION_MESSAGE);
      }
    }//GEN-LAST:event_updateActionPerformed

    public ArrayList Assigndata()
    {
             getdata.add(faculty);
             getdata.add(section);
             getdata.add(semester);
             getdata.add(lecture);
             getdata.add(deadline);
             getdata.add(this.question.getText());
         return getdata;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addquestion dialog = new addquestion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
     ArrayList getdata = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JTextArea question;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
